const SECTION_OPTIONS = [
  'Mathematics',
  'Mapeh / TLE',
  'Computers',
  'English',
  'Creative Arts',
  'Filipino',
  'PE and Sports',
  'History / Geography',
  'Cooking',
  'Science',
  'Reading and Writing',
  'Literature',
  'Gardening',
  'Fiction',
  'High School Fiction',
  'High School Reference',
  'Guinness Book of World Records',
  'Religion, Spirituality, Philosophy, Occult',
  'Biography',
  'Marketing',
  'Accounting',
  'Parenting',
  'Technology',
  'Dictionaries, Quotations, Thesaurus',
  'Modern Fiction',
  'Reference, Encyclopedia, Handbook',
  'Classic Books',
  'Award Winning Books',
  'Novels Produced into Films',
  'Readings in Transpersonal Psychology',
  'Five Pillars of Total Education',
  'Reading of Theosophical Education',
  'The Ageless Wisdom',
  'Rizal Books',
  'Filipiniana Collection',
  'PE Rhythmical Act. Compilation',
  'The Harvard Classics',
  'Best Loved Books',
  'Nonfiction',
  'High School',
  'Bibliography',
  'Reference',
  'Thesis',
  'Capstone Project',
  'Research Paper',
  'Other',
  'Circulation',
  'Filipiana',
  'General Reference',
  'General Collection',
  'Non-Fiction',
  'Reserve',
  'Periodicals',
  'Journals & Magazines',
  'Newspapers',
  'Thesis & Dissertations',
  'Research & Special Projects',
  'Graduate Studies',
  'Electronic Resources',
  'Audio-Visual',
  'Special Collection',
  'Vertical Files',
  'Textbooks',
  'Children’s Section',
  'Young Adult Section',
].sort((a, b) => a.localeCompare(b));

export default SECTION_OPTIONS;
